/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ok.then;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    public static void getGreeting(){
        System.out.println("vibe");
    }
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        
    }
}
